BookManagementFinalTest/Controllers/AuthorController.cs
using BookManagementFinalTest.Models;
using BookManagementFinalTest.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace BookManagementFinalTest.Controllers
{
    public class AuthorController : Controller
    {
        #region Variable declarations
        /// <summary>The author repository</summary>
        private readonly IAuthorRepository _AuthorRepository;
        #endregion

        #region Constructor
        /// <summary>Initializes a new instance of the <see cref="AuthorController"/> class.</summary>
        /// <param name="AuthorRepository">The author repository.</param>
        public AuthorController(IAuthorRepository AuthorRepository)
        {
            _AuthorRepository = AuthorRepository;
        }
        #endregion

        #region Index method
        // GET: Author
        // Returns all author with pagination
        public IActionResult Index(int page = 1, int pageSize = 3)
        {
            return View(_AuthorRepository.GetAll(page, pageSize));
        }
        #endregion

        #region Details method
        // GET: Author/Details
        // Returns author details with matching id
        public IActionResult Details(int? id)
        {
            var author = _AuthorRepository.GetAuthor(id);

            if (author == null)
            {
                Response.StatusCode = 404;
                return View("AuthorNotFound", id);
            }

            return View(author);
        }
        #endregion

        #region Save method
        // GET: Author/Save
        // Saves or edits author details
        public IActionResult Save(int id)
        {
            var author = _AuthorRepository.GetAuthor(id);

            if (id == 0)
                author = new Author();

            if (author == null)
            {
                Response.StatusCode = 404;
                return View("AuthorNotFound", id);
            }

            return View(author);
        }

        // POST: Book/Save
        // Saves or edits author details
        [HttpPost]
        public IActionResult Save(Author author)
        {
            if (author.Id == 0)
            {
                var isEmailAvailable = _AuthorRepository.GetEmail(author.Email);
                var isContactAvailable = _AuthorRepository.GetContact(author.Contact);

                if (isEmailAvailable != null)
                {
                    ModelState.AddModelError("Email", "Email already exists.");
                    return View(author);
                }
                else if (isContactAvailable != null)
                {
                    ModelState.AddModelError("Contact", "Contact already exists.");
                    return View(author);
                }
            }

            if (ModelState.IsValid)
            {
                _AuthorRepository.SaveAuthor(author);
                return RedirectToAction("Index");
            }
            return View(author);
        }
        #endregion

        #region Delete method
        // GET: Book/Delete
        // Deletes book with specified id
        public IActionResult Delete(int id)
        {
            var author = _AuthorRepository.GetAuthor(id);

            if (author == null)
            {
                Response.StatusCode = 404;
                return View("AuthorNotFound", id);
            }

            return View(author);
        }

        // POST: Book/Delete
        // Confirms delete
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            _AuthorRepository.DeleteAuthor(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

BookManagementFinalTest/Controllers/BookController.cs
using BookManagementFinalTest.Models;
using BookManagementFinalTest.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace BookManagementFinalTest.Controllers
{
    public class BookController : Controller
    {
        #region Variable declarations
        /// <summary>The book repository</summary>
        private readonly IBookRepository _bookRepository;
        #endregion

        #region Constructor
        /// <summary>Initializes a new instance of the <see cref="BookController"/> class.</summary>
        /// <param name="bookRepository">The book repository.</param>
        public BookController(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        #endregion

        #region Index method
        // GET: Book
        // Returns all books
        public IActionResult Index(string search = null)
        {
            if (!string.IsNullOrEmpty(search))
                return View(_bookRepository.SearchBook(search));

            return View(_bookRepository.GetAll());
        }
        #endregion

        #region Details method
        // GET: Book/Details
        // Returns details of specific book using id
        public IActionResult Details(int? id)
        {
            var book = _bookRepository.GetBook(id);

            if (book == null)
            {
                Response.StatusCode = 404;
                return View("BookNotFound", id);
            }

            return View(book);
        }
        #endregion

        #region Save method
        // GET: Book/Save
        // Shows form to add new book else shows book to edit
        [HttpGet]
        public IActionResult Save(int id)
        {
            var book = _bookRepository.GetBook(id);
            ViewBag.AuthorId = _bookRepository.GetAuthors();

            if (id == 0)
                book = new Book();

            if (book == null)
            {
                Response.StatusCode = 404;
                return View("BookNotFound", id);
            }

            return View(book);
        }

        // POST: Book/Save
        // Posts book details
        [HttpPost]
        public IActionResult Save(Book book)
        {
            if (ModelState.IsValid)
            {
                _bookRepository.SaveBook(book);
                return RedirectToAction("Index");
            }

            return View(book);
        }
        #endregion

        #region Delete method
        // GET: Book/Delete
        // Returns book details to delete
        [HttpGet]
        [ActionName("Delete")]
        public IActionResult Delete(int id)
        {
            var book = _bookRepository.GetBook(id);

            if (book == null)
            {
                Response.StatusCode = 404;
                return View("BookNotFound", id);
            }

            return View(book);
        }

        // POST: Book/Delete
        // Confirms delete
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            _bookRepository.DeleteBook(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

BookManagementFinalTest/Views/Shared/AuthorNotFound.cshtml
@model int
@{
    ViewBag.Title = "404 Error";
}

<div class="alert alert-danger mt-1 mb-1">
    <h4>404 Not Found Error :</h4>
    <hr />
    <h5>
        Author with ID = @Model cannot be found
    </h5>
</div>

<a asp-controller="author" asp-action="index" class="btn btn-outline-success"
   style="width:auto">Click here to see the list of all Author</a>

BookManagementFinalTest/Views/Shared/BookNotFound.cshtml
@model int
@{
    ViewBag.Title = "404 Error";
}

<div class="alert alert-danger mt-1 mb-1">
    <h4>404 Not Found Error :</h4>
    <hr />
    <h5>
        Book with ID = @Model cannot be found
    </h5>
</div>

<a asp-controller="book" asp-action="index" class="btn btn-outline-success"
   style="width:auto">Click here to see the list of all Books</a>

BookManagementFinalTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookManagementFinalTest</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
    <link href="~/css/toastr.min.css" rel="stylesheet" />
    <script src="~/js/toastr.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/site.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
        <img src="~/images/logo.jpg" asp-append-version="true" alt="logo" class="img-fluid navbar-brand" width="40" height="40" />
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a asp-action="Index" asp-controller="Book" class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">Book</a>
                    <div class="dropdown-menu">
                        <a asp-action="Index" asp-controller="Book" class="dropdown-item">Show books</a>
                        <a asp-action="Save" asp-controller="Book" class="dropdown-item">Add book</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a asp-action="Index" asp-controller="Book" class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">Author</a>
                    <div class="dropdown-menu">
                        <a asp-action="Index" asp-controller="Author" class="dropdown-item">Show authors</a>
                        <a asp-action="Save" asp-controller="Author" class="dropdown-item">Add author</a>
                    </div>
                </li>
            </ul>
        </div>
        <form asp-action="Index" asp-controller="book" method="post">
            <div class="input-group">
                <input type="text" name="search" id="search" class="form-control" placeholder="Search book..." />
                <div class="input-group-append">
                    <input type="submit" value="search" class="btn btn-info" />
                </div>
            </div>
        </form>
    </nav>

    <div class="container">
        @RenderBody()
    </div>


    <footer class="footer">
        <div class="container text-center">
            &copy; 2019 - Book Management Final Test
        </div>
    </footer>
</body>
</html>